TicariOtomasyonProje/TicariOtomasyonProje/Controllers/BuyPageController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TicariOtomasyonProje.Models;

namespace TicariOtomasyonProje.Controllers
{
    [AllowAnonymous]
    public class BuyPageController : Controller
    {
        ProductManager pm = new ProductManager(new EFProductDal());
        // GET: BuyPage
        SalePageModel spm = new SalePageModel();

        public ActionResult Buy()
        {
            return View();
        }


        public ActionResult Deneme(int id)
        {
            /*
            Context c = new Context();
            p = (string)Session["BookName"];
            var user = c.Books.Where(x => x.BookName == p).Select(y => y.BookID).FirstOrDefault();
            var values = pm.GetByID(user);
            return View(values);*/

            //int id;
            //var result = pm.GetListByID(id);
            //return View(result);
           

            spm.Book = pm.GetListByID(id);
            return View(spm);
        }

        public ActionResult SameCategory(int cId)
        {

            Context c = new Context();
            var category = c.Books.Where(x=>x.CategoryID==cId);

            return View();
        }

    }
}

TicariOtomasyonProje/TicariOtomasyonProje/Controllers/CustomerLoginController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrate;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace TicariOtomasyonProje.Controllers
{
    [AllowAnonymous]
    public class CustomerLoginController : Controller
    {
        // GET: CustomerLogin
        CustomerManager cm = new CustomerManager(new EFCustomerDal());

        //[HttpGet]
        /* public ActionResult Login()
         {
             return View();
         }

         [HttpPost]
         public ActionResult Login(Customer p)
         {
             Context c = new Context();
             var user = c.Customers.FirstOrDefault(x => x.CustomerName == p.CustomerName && x.CAddressID == p.CAddressID);
             if (user != null)
             {
                 FormsAuthentication.SetAuthCookie(user.CustomerName, false);
                 Session["CustomerName"] = user.CustomerName;
                 return RedirectToAction("Deneme", "SalePage");
             }
             else
             {
                 return RedirectToAction("Login");
             }

         }*/

        public ActionResult Login(string p)
        {
              Context c = new Context();
              p = (string)Session["CustomerName"];
              var user = c.Customers.Where(x => x.CustomerName == p).Select(y => y.CustomerID).FirstOrDefault();
              var values = cm.GetListById(user);
              return View(values);
        }



        [HttpGet]
        public ActionResult DenemeLog()
        {
            
            return View();
        }
        Context c = new Context();

        [HttpPost]
        public ActionResult DenemeLog(Customer p)
        {
            
            var user = c.Customers.FirstOrDefault(x => x.CustomerName == p.CustomerName && x.CustomerPassword == p.CustomerPassword);
            if (user != null)
            {
                FormsAuthentication.SetAuthCookie(user.CustomerName, false);
                Session["CustomerName"] = user.CustomerName.ToString();
                return RedirectToAction("Deneme", "SalePage");
            }
           
                return RedirectToAction("Index","AdminLogin");
            
        }




        [HttpGet]
        public ActionResult RegisterV3()
        {
            return View();
        }



        [HttpPost]
        public ActionResult RegisterV3(Customer c)
        {
            if (ModelState.IsValid)
            {
                cm.CustomerAdd(c);
                return RedirectToAction("DenemeLog");
            }

            else
            {
                return View();
            }
        }

    }
}

TicariOtomasyonProje/TicariOtomasyonProje/Controllers/CustomerSalePageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TicariOtomasyonProje.Controllers
{[AllowAnonymous]
    public class CustomerSalePageController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

TicariOtomasyonProje/TicariOtomasyonProje/Views/CustomerSalePage/Index.cshtml
@using EntityLayer.Concrate
@model List<Book>
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Los Pollos Hermanos Kitapçılık</title>
    <link href="~/DenemeMenü/NavBarCss.css" rel="stylesheet" />
    <link href="~/DenemeMenü/NavBarCss2.css" rel="stylesheet" />
    <link href="~/DenemeMenü/HeaderCss.css" rel="stylesheet" />
    <link href="~/DenemeMenü/SellCss.css" rel="stylesheet" />
    <link href="~/DenemeMenü/CardCss.css" rel="stylesheet" />
    <link href="~/DenemeMenü/ButtonCss.css" rel="stylesheet" />
    <link href="~/DenemeMenü/FooterCss.css" rel="stylesheet" />

</head>
<body>
    <nav class="navbar">
        <div class="nav">
            <img src="~/Resimler/lospoloshermanos3.jpg" class="brand-logo" alt=""><a href="/SalePage/Deneme"></a>

            <div class="nav-items">

                <div class="search">
                    <input type="text" class="search-box" placeholder="search brand, product">
                    <button class="search-btn">Ara</button>
                </div>

                <button class="btn-kayit" type="button" onclick="location.href='@Url.Action("DenemeLog", "CustomerLogin" )'">Giriş Yap</button>
                <button class="btn-giris">Sepetim</button>

            </div>
        </div>
        <ul class="links-container">
            <li class="link-item"> <a href="/SalePage/Deneme" class="link"> Ana Sayfa</a></li>
            @foreach (var item in Model)
            {
                <li class="link-item"><a href="#" class="link">@item.Category</a></li>

            }
        </ul>

    </nav>


    <section class="product">
        <h2 class="product-category">Vitrin Ürünleri</h2>
    </section>

    <div class="product-container">
        @foreach (var item in Model)
        {
            <div class="product-card">
                <div class="product-image">
                    <span class="discount-tag">50% off</span>
                    <img src="~/Resimler/Metro2033.jpg" class="product-thumb" alt="">

                    <button type="button" class="card-btn" onclick="location.href='@Url.Action("Deneme", "BuyPage" )'">Satın Al</button>


                </div>
                <div class="product-info">
                    <h2 class="product-brand">@item.BookName</h2>
                    <p class="product-short-des">@item.Category</p>
                    <span class="price">$20</span><span class="actual-price">$40</span>
                </div>
            </div>

        }
    </div>





    <footer>
        <div class="footer-content">
            <img src="img/light-logo.png" class="logo" alt="">
            <div class="footer-ul-container">
                <ul class="category">
                    <li class="category-title">men</li>
                    <li><a href="#" class="footer-link">t-shirts</a></li>

                </ul>
                <ul class="category">
                    <li class="category-title">women</li>
                    <li><a href="#" class="footer-link">t-shirts</a></li>

                </ul>
            </div>
        </div>
    </footer>

    <footer>
        <p class="footer-title">about company</p>
        <p class="info">Lorem ipsum, dolor sit amet consectetur adipisicing elit. Repellat tempore ad suscipit, eos eius quisquam sed optio nisi quaerat fugiat ratione et vero maxime praesentium, architecto minima reiciendis iste quo deserunt assumenda alias ducimus. Ullam odit maxime id voluptates rerum tenetur corporis laboriosam! Cum error ipsum laborum tempore in rerum necessitatibus nostrum nobis modi! Debitis adipisci illum nemo aperiam sed, et accusamus ut officiis. Laborum illo exercitationem quo culpa reprehenderit excepturi distinctio tempore cupiditate praesentium nisi ut iusto, assumenda perferendis facilis voluptas autem fuga sunt ab debitis voluptatum harum eum. Asperiores, natus! Est deserunt incidunt quasi placeat omnis, itaque harum?</p>
        <p class="info">support emails - help@clothing.com, customersupport@clothing.com</p>
        <p class="info">telephone - 180 00 00 001, 180 00 00 002</p>
        <div class="footer-social-container">
            <div>
                <a href="#" class="social-link">terms & services</a>
                <a href="#" class="social-link">privacy page</a>
            </div>
            <div>
                <a href="#" class="social-link">instagram</a>
                <a href="#" class="social-link">facebook</a>
                <a href="#" class="social-link">twitter</a>
            </div>
        </div>
        <p class="footer-credit">Clothing, Best apparels online store</p>
    </footer>


</body>
</html>